# Generated by Django 6.0.4 on 2026-06-02 18:56

import django.db.models.deletion
import myteacher.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myteacher', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='subject_type',
            field=models.CharField(choices=[('1', '1St'), ('2', '2nd'), ('0', 'NA')], max_length=1, verbose_name='Type'),
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('mark_id', models.CharField(default=myteacher.models.Mark.generate_mark_id, max_length=6, primary_key=True, serialize=False, unique=True, verbose_name='Mark ID')),
                ('objective_mark', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('subjective_mark', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('class_test_mark', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('practical_mark', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student', verbose_name='Student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myteacher.subject', verbose_name='Subject')),
            ],
            options={
                'verbose_name': 'Student Mark',
                'verbose_name_plural': 'Student Marks',
            },
        ),
    ]
