# Generated by Django 6.0.4 on 2026-06-02 19:08

import django.db.models.deletion
import myteacher.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myteacher', '0002_alter_subject_subject_type_mark'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_id', models.CharField(max_length=20, unique=True, verbose_name='Teacher ID')),
                ('teacher_name', models.CharField(max_length=100, verbose_name='Teacher Name')),
                ('designation', models.CharField(max_length=50, verbose_name='Designation')),
                ('mobile', models.CharField(max_length=15, verbose_name='Mobile Number')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('teacher_img', models.ImageField(upload_to='teachers/', verbose_name='Teacher Photo')),
                ('assigned_class', models.CharField(choices=[('6', 'Class 6'), ('7', 'Class 7'), ('8', 'Class 8'), ('9', 'Class 9'), ('10', 'Class 10')], max_length=2, verbose_name='Assigned Class')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='System User')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherSubjectAssignment',
            fields=[
                ('assisngsubid', models.CharField(default=myteacher.models.TeacherSubjectAssignment.generate_assign_id, max_length=6, primary_key=True, serialize=False, unique=True, verbose_name='Assign ID')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myteacher.subject', verbose_name='Subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myteacher.teacher', verbose_name='Teacher')),
            ],
            options={
                'verbose_name': 'Subject Assignment',
                'verbose_name_plural': 'Subject Assignments',
            },
        ),
    ]
