# Generated by Django 6.0.4 on 2026-06-03 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myteacher', '0003_teacher_teachersubjectassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='mark',
            name='exam_type',
            field=models.CharField(choices=[('Half Yearly', 'Half Yearly'), ('Annual', 'Annual'), ('Pretest', 'Pretest'), ('Test', 'Test')], default='Half Yearly', max_length=20, verbose_name='Exam Type'),
        ),
    ]
