# Generated by Django 6.0.4 on 2026-06-03 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myteacher', '0004_mark_exam_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='class_teacher_of',
            field=models.CharField(blank=True, choices=[('6', 'Class 6'), ('7', 'Class 7'), ('8', 'Class 8'), ('9', 'Class 9'), ('10', 'Class 10')], max_length=2, null=True, verbose_name='Class Teacher of (Class)'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='is_class_teacher',
            field=models.BooleanField(default=False, verbose_name='Is Class Teacher?'),
        ),
    ]
