# Generated by Django 6.0.4 on 2026-06-03 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myteacher', '0005_teacher_class_teacher_of_teacher_is_class_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='designation',
            field=models.CharField(choices=[('Headmaster', 'Headmaster'), ('Assistant Headmaster', 'Assistant Headmaster'), ('Senior Teacher', 'Senior Teacher'), ('Assistant Teacher', 'Assistant Teacher')], max_length=50, verbose_name='Designation'),
        ),
    ]
