# Generated by Django 6.0.4 on 2026-06-05 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myteacher', '0006_alter_teacher_designation'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamRoutine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(max_length=100, verbose_name='Exam Name')),
                ('exam_class', models.CharField(choices=[('6', 'Class 6'), ('7', 'Class 7'), ('8', 'Class 8'), ('9', 'Class 9'), ('10', 'Class 10')], max_length=2, verbose_name='Class')),
                ('subject', models.CharField(max_length=100, verbose_name='Subject')),
                ('exam_date', models.DateField(verbose_name='Exam Date')),
                ('exam_time', models.CharField(max_length=50, verbose_name='Exam Time')),
            ],
            options={
                'verbose_name': 'Exam Routine',
                'verbose_name_plural': 'Exam Routines',
            },
        ),
        migrations.AddField(
            model_name='teacher',
            name='routine_permission',
            field=models.BooleanField(default=False, verbose_name='Allow Routine Creation'),
        ),
        migrations.CreateModel(
            name='AdmitCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(max_length=100, verbose_name='Exam Name')),
                ('generated_date', models.DateTimeField(auto_now_add=True, verbose_name='Generated Date')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student', verbose_name='Student')),
            ],
            options={
                'verbose_name': 'Admit Card',
                'verbose_name_plural': 'Admit Cards',
            },
        ),
    ]
