# Generated by Django 6.0.4 on 2026-06-06 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myteacher', '0007_examroutine_teacher_routine_permission_admitcard'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examroutine',
            options={},
        ),
        migrations.RemoveField(
            model_name='examroutine',
            name='exam_class',
        ),
        migrations.RemoveField(
            model_name='examroutine',
            name='exam_name',
        ),
        migrations.RemoveField(
            model_name='examroutine',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='routine_permission',
        ),
        migrations.AddField(
            model_name='examroutine',
            name='class_name',
            field=models.CharField(choices=[('6', 'Class 6'), ('7', 'Class 7'), ('8', 'Class 8'), ('9', 'Class 9'), ('10', 'Class 10')], default='6', max_length=2),
        ),
        migrations.AddField(
            model_name='examroutine',
            name='exam_type',
            field=models.CharField(choices=[('Half Yearly', 'Half Yearly'), ('Annual Exam', 'Annual Exam'), ('Test Exam', 'Test Exam')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='examroutine',
            name='exam_year',
            field=models.IntegerField(default=2026),
        ),
        migrations.AddField(
            model_name='examroutine',
            name='group_name',
            field=models.CharField(blank=True, choices=[('Science', 'Science'), ('Commerce', 'Commerce'), ('Arts', 'Arts'), ('', 'General')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='examroutine',
            name='subject_code',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='examroutine',
            name='subject_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='examroutine',
            name='exam_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='examroutine',
            name='exam_time',
            field=models.CharField(default='10:00 AM', max_length=50),
        ),
        migrations.DeleteModel(
            name='AdmitCard',
        ),
    ]
