# Generated by Django 6.0.4 on 2026-06-20 21:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myteacher', '0008_alter_examroutine_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachersubjectassignment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Assigned On'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='teachersubjectassignment',
            unique_together={('teacher', 'subject')},
        ),
        migrations.CreateModel(
            name='TeacherClassAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_level', models.CharField(choices=[('6', 'Class 6'), ('7', 'Class 7'), ('8', 'Class 8'), ('9', 'Class 9'), ('10', 'Class 10')], max_length=2, verbose_name='Class')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Assigned On')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_assignments', to='myteacher.teacher', verbose_name='Teacher')),
            ],
            options={
                'verbose_name': 'Teacher Class Assignment',
                'verbose_name_plural': 'Teacher Class Assignments',
                'unique_together': {('teacher', 'class_level')},
            },
        ),
    ]
