# Generated by Django 6.0.4 on 2026-06-21 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myteacher', '0009_teachersubjectassignment_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mark',
            name='exam_year',
            field=models.IntegerField(default=2026, verbose_name='Exam Year'),
        ),
    ]
