# Generated by Django 6.0.4 on 2026-06-21 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myteacher', '0010_mark_exam_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='full_mark',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Full Mark'),
        ),
    ]
