# Generated by Django 6.0.4 on 2026-06-22 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myteacher', '0011_subject_full_mark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='subject_type',
            field=models.CharField(choices=[('1', '1st'), ('2', '2nd'), ('4', '4th'), ('0', 'NA')], max_length=1, verbose_name='Type'),
        ),
    ]
