# Generated by Django 6.0.4 on 2026-06-22 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myteacher', '0012_alter_subject_subject_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='religion',
            field=models.CharField(choices=[('None', 'None'), ('Islam', 'Islam'), ('Hindu', 'Hindu'), ('Buddhist', 'Buddhist'), ('Christian', 'Christian')], default='None', max_length=10, verbose_name='Religion'),
        ),
    ]
