# Generated by Django 6.0.4 on 2026-06-26 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myteacher', '0013_subject_religion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examroutine',
            name='exam_type',
            field=models.CharField(choices=[('Half Yearly', 'Half Yearly Examination'), ('Annual Exam', 'Annual Examination'), ('Pre Test Exam', 'Pre Test Examination'), ('Test Exam', 'Test Examination')], default='', max_length=20),
        ),
    ]
