# Generated by Django 6.0.4 on 2026-07-16 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myteacher', '0014_alter_examroutine_exam_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='subject_code',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Subject Code'),
        ),
    ]
