# Generated by Django 6.0.4 on 2026-09-22 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myteacher', '0015_subject_subject_code'),
        ('students', '0010_studentresultpublication'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mark',
            options={},
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('father_name', models.CharField(max_length=150)),
                ('mother_name', models.CharField(max_length=150)),
                ('class_level', models.CharField(max_length=2)),
                ('group', models.CharField(blank=True, max_length=50)),
                ('roll', models.CharField(blank=True, max_length=30)),
                ('registration', models.CharField(blank=True, max_length=50)),
                ('session', models.CharField(blank=True, max_length=30)),
                ('date_of_birth', models.CharField(blank=True, max_length=30)),
                ('gender', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('current', 'Current Student'), ('ssc_passed', 'SSC Passed')], default='current', max_length=20)),
                ('ssc_year', models.CharField(blank=True, max_length=4)),
                ('ssc_board', models.CharField(blank=True, max_length=100)),
                ('candidate_type', models.CharField(blank=True, default='Regular', max_length=30)),
                ('gpa', models.CharField(blank=True, max_length=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='testimonial_record', to='students.student', verbose_name='Student')),
            ],
            options={
                'verbose_name': 'Student Mark',
                'verbose_name_plural': 'Student Marks',
            },
        ),
    ]
