# Generated by Django 6.0.4 on 2026-09-22 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myteacher', '0016_alter_mark_options_testimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='serial_number',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='Serial Number'),
        ),
    ]
