# Generated by Django 6.0.4 on 2026-09-22 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myteacher', '0017_testimonial_serial_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='generated_date',
            field=models.DateField(blank=True, null=True, verbose_name='Generated Date'),
        ),
    ]
