# Generated by Django 6.1.2 on 2026-10-10 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myteacher', '0018_testimonial_generated_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='group_name',
            field=models.CharField(blank=True, choices=[('', 'General'), ('Science', 'Science'), ('Commerce', 'Commerce'), ('Arts', 'Arts')], default='', help_text='For classes 9-10; General subjects are available to all groups.', max_length=20, verbose_name='Group'),
        ),
        migrations.AlterField(
            model_name='examroutine',
            name='group_name',
            field=models.CharField(blank=True, choices=[('', 'General'), ('Science', 'Science'), ('Commerce', 'Commerce'), ('Arts', 'Arts')], max_length=20, null=True),
        ),
    ]
