# Generated by Django 6.0.4 on 2026-06-01 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='students/', verbose_name='Student Photo')),
                ('full_name', models.CharField(max_length=100, verbose_name='Full Name')),
                ('father_name', models.CharField(max_length=100, verbose_name="Father's Name")),
                ('mother_name', models.CharField(max_length=100, verbose_name="Mother's Name")),
                ('student_id', models.CharField(max_length=7, unique=True, verbose_name='Student ID (7 Digits)')),
                ('current_class', models.CharField(choices=[('6', 'Class 6'), ('7', 'Class 7'), ('8', 'Class 8'), ('9', 'Class 9'), ('10', 'Class 10')], max_length=2, verbose_name='Class')),
                ('class_roll', models.PositiveIntegerField(verbose_name='Class Roll')),
                ('shift', models.CharField(default='Day', max_length=10, verbose_name='Shift')),
                ('mobile_num', models.CharField(max_length=15, verbose_name='Mobile Number')),
                ('group', models.CharField(blank=True, choices=[(None, 'None'), ('Science', 'Science'), ('Arts', 'Arts'), ('Commerce', 'Commerce')], max_length=20, null=True, verbose_name='Group')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
            },
        ),
    ]
