# Generated by Django 6.0.4 on 2026-07-03 18:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_student_gender'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['class_roll', 'full_name'], 'verbose_name': 'Student', 'verbose_name_plural': 'Students'},
        ),
        migrations.AddField(
            model_name='student',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='generated_password',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Auto Generated Password'),
        ),
        migrations.AddField(
            model_name='student',
            name='login_enabled',
            field=models.BooleanField(default=True, verbose_name='Login Enabled'),
        ),
        migrations.AddField(
            model_name='student',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_profile', to=settings.AUTH_USER_MODEL, verbose_name='System User'),
        ),
        migrations.CreateModel(
            name='StudentAdmitCardSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_level', models.CharField(choices=[('6', 'Class 6'), ('7', 'Class 7'), ('8', 'Class 8'), ('9', 'Class 9'), ('10', 'Class 10')], max_length=2, verbose_name='Class')),
                ('exam_type', models.CharField(max_length=50, verbose_name='Exam Type')),
                ('exam_year', models.IntegerField(verbose_name='Exam Year')),
                ('is_enabled', models.BooleanField(default=False, verbose_name='Enable Admit Card for Students')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
            ],
            options={
                'verbose_name': 'Student Admit Card Setting',
                'verbose_name_plural': 'Student Admit Card Settings',
                'ordering': ['-exam_year', 'exam_type', 'class_level'],
                'unique_together': {('class_level', 'exam_type', 'exam_year')},
            },
        ),
        migrations.CreateModel(
            name='StudentPromotionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_class', models.CharField(choices=[('6', 'Class 6'), ('7', 'Class 7'), ('8', 'Class 8'), ('9', 'Class 9'), ('10', 'Class 10')], max_length=2, verbose_name='From Class')),
                ('to_class', models.CharField(choices=[('6', 'Class 6'), ('7', 'Class 7'), ('8', 'Class 8'), ('9', 'Class 9'), ('10', 'Class 10')], max_length=2, verbose_name='To Class')),
                ('promoted_at', models.DateTimeField(auto_now_add=True, verbose_name='Promoted On')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_history', to='students.student', verbose_name='Student')),
            ],
            options={
                'verbose_name': 'Student Promotion History',
                'verbose_name_plural': 'Student Promotion Histories',
                'ordering': ['-promoted_at'],
            },
        ),
    ]
