# Generated by Django 6.0.4 on 2026-07-03 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_alter_student_options_student_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAdmitCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_level', models.CharField(choices=[('6', 'Class 6'), ('7', 'Class 7'), ('8', 'Class 8'), ('9', 'Class 9'), ('10', 'Class 10')], max_length=2, verbose_name='Class')),
                ('exam_type', models.CharField(max_length=50, verbose_name='Exam Type')),
                ('exam_year', models.IntegerField(verbose_name='Exam Year')),
                ('exam_title', models.CharField(max_length=100, verbose_name='Exam Title')),
                ('generated_at', models.DateTimeField(auto_now=True, verbose_name='Generated On')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_admit_cards', to='students.student', verbose_name='Student')),
            ],
            options={
                'verbose_name': 'Saved Admit Card',
                'verbose_name_plural': 'Saved Admit Cards',
                'ordering': ['-exam_year', 'exam_type', 'student__class_roll'],
                'unique_together': {('student', 'exam_type', 'exam_year')},
            },
        ),
    ]
