# Generated by Django 6.0.4 on 2026-07-03 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_save_admit_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='profile_ticker',
            field=models.TextField(blank=True, help_text='Student-specific message shown on the profile page.', null=True, verbose_name='Profile Ticker Message'),
        ),
    ]
