# Generated by Django 6.0.4 on 2026-07-03 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_student_profile_ticker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='profile_ticker',
        ),
        migrations.CreateModel(
            name='StudentTicker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=120, verbose_name='Ticker Title')),
                ('message', models.TextField(verbose_name='Ticker Message')),
                ('show_to_all', models.BooleanField(default=False, verbose_name='Show to All Students')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated On')),
                ('target_students', models.ManyToManyField(blank=True, help_text='Leave blank if showing to all students, otherwise select specific students.', related_name='tickers', to='students.student', verbose_name='Target Students')),
            ],
            options={
                'verbose_name': 'Student Ticker',
                'verbose_name_plural': 'Student Tickers',
                'ordering': ['-is_active', '-updated_at'],
            },
        ),
    ]
