# Generated by Django 5.2.2 on 2026-07-07 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_student_user_id_column'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentResultPublication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_level', models.CharField(choices=[('6', 'Class 6'), ('7', 'Class 7'), ('8', 'Class 8'), ('9', 'Class 9'), ('10', 'Class 10')], max_length=2, verbose_name='Class')),
                ('exam_type', models.CharField(max_length=50, verbose_name='Exam Type')),
                ('exam_year', models.IntegerField(verbose_name='Exam Year')),
                ('is_published', models.BooleanField(default=False, verbose_name='Published')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated On')),
            ],
            options={
                'verbose_name': 'Student Result Publication',
                'verbose_name_plural': 'Student Result Publications',
                'ordering': ['-exam_year', 'exam_type', 'class_level'],
                'unique_together': {('class_level', 'exam_type', 'exam_year')},
            },
        ),
    ]
