# Generated by Django 6.0.4 on 2026-04-26 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_gallery_alter_notice_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='স্লাইডার শিরোনাম/ক্যাপশন')),
                ('image', models.ImageField(upload_to='sliders/', verbose_name='স্লাইডার ইমেজ')),
                ('is_active', models.BooleanField(default=True, verbose_name='অ্যাক্টিভ আছে?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': '২. হোমপেজ স্লাইডার',
            },
        ),
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name_plural': '৩. ফটোগ্যালারি'},
        ),
        migrations.AlterModelOptions(
            name='notice',
            options={'ordering': ['-created_at'], 'verbose_name_plural': '১. নোটিশ বোর্ড'},
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(upload_to='gallery/', verbose_name='ছবি'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='title',
            field=models.CharField(blank=True, max_length=100, verbose_name='ছবির শিরোনাম (ঐচ্ছিক)'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='description',
            field=models.TextField(verbose_name='বিস্তারিত'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='অ্যাক্টিভ আছে?'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='title',
            field=models.CharField(max_length=200, verbose_name='নোটিশের শিরোনাম'),
        ),
    ]
