# Generated by Django 6.0.4 on 2026-04-26 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_slider_alter_gallery_options_alter_notice_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='আমাদের সম্পর্কে', max_length=200, verbose_name='শিরোনাম')),
                ('description', models.TextField(verbose_name='স্কুলের বর্ণনা/ইতিহাস')),
                ('about_image', models.ImageField(upload_to='about/', verbose_name='স্কুলের ছবি (About Image)')),
            ],
            options={
                'verbose_name_plural': '৪. আমাদের সম্পর্কে (School Info)',
            },
        ),
    ]
