# Generated by Django 6.0.4 on 2026-04-26 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_schoolinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='শিক্ষকের নাম')),
                ('designation', models.CharField(max_length=100, verbose_name='পদবী')),
                ('image', models.ImageField(upload_to='teachers/', verbose_name='ছবি')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='ফোন নম্বর')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ইমেইল')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ক্রমিক নং (সিরিয়াল)')),
            ],
            options={
                'verbose_name_plural': '৫. শিক্ষকবৃন্দ',
                'ordering': ['order'],
            },
        ),
    ]
