# Generated by Django 6.0.4 on 2026-04-26 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='about_slider/', verbose_name='স্লাইডার ছবি')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': '৫. সম্পর্কে সেকশন স্লাইডার',
            },
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ['order'], 'verbose_name_plural': '৬. শিক্ষক ও কর্মচারীবৃন্দ'},
        ),
        migrations.RemoveField(
            model_name='schoolinfo',
            name='about_image',
        ),
        migrations.AlterField(
            model_name='teacher',
            name='name',
            field=models.CharField(max_length=100, verbose_name='নাম'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='ক্রমিক নং (সিরিয়াল)'),
        ),
    ]
