# Generated by Django 6.0.4 on 2026-04-26 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_aboutslider_alter_teacher_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolinfo',
            name='about_image',
            field=models.ImageField(blank=True, null=True, upload_to='about/', verbose_name='স্কুলের মূল ছবি'),
        ),
    ]
