# Generated by Django 6.0.4 on 2026-04-26 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_schoolinfo_about_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='about_slider/', verbose_name='স্লাইডার ছবি')),
            ],
            options={
                'verbose_name_plural': 'অ্যাবাউট সেকশন ছবিগুলো',
            },
        ),
        migrations.DeleteModel(
            name='AboutSlider',
        ),
        migrations.AlterModelOptions(
            name='schoolinfo',
            options={'verbose_name_plural': '৪. আমাদের সম্পর্কে'},
        ),
        migrations.RemoveField(
            model_name='schoolinfo',
            name='about_image',
        ),
        migrations.AlterField(
            model_name='gallery',
            name='title',
            field=models.CharField(blank=True, max_length=100, verbose_name='ছবির শিরোনাম'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='title',
            field=models.CharField(max_length=200, verbose_name='স্লাইডার শিরোনাম'),
        ),
        migrations.AddField(
            model_name='aboutimage',
            name='school_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main_app.schoolinfo'),
        ),
    ]
