# Generated by Django 6.0.4 on 2026-04-26 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_aboutimage_delete_aboutslider_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralTeacher',
            fields=[
            ],
            options={
                'verbose_name': 'সহকারী শিক্ষক',
                'verbose_name_plural': '৮. সহকারী শিক্ষকবৃন্দ',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main_app.teacher',),
        ),
        migrations.CreateModel(
            name='Headmaster',
            fields=[
            ],
            options={
                'verbose_name': 'প্রতিষ্ঠান প্রধান',
                'verbose_name_plural': '৭. প্রতিষ্ঠান প্রধান',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main_app.teacher',),
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
            ],
            options={
                'verbose_name': 'কর্মচারী',
                'verbose_name_plural': '৯. কর্মচারীবৃন্দ',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main_app.teacher',),
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ['order'], 'verbose_name_plural': '৬. সকল শিক্ষক ও কর্মচারী'},
        ),
    ]
