# Generated by Django 6.0.4 on 2026-04-26 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_generalteacher_headmaster_staff_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutimage',
            options={},
        ),
        migrations.AlterModelOptions(
            name='generalteacher',
            options={'verbose_name': 'সহকারী শিক্ষক', 'verbose_name_plural': '৭. সহকারী শিক্ষকবৃন্দ'},
        ),
        migrations.AlterModelOptions(
            name='headmaster',
            options={'verbose_name': 'প্রতিষ্ঠান প্রধান', 'verbose_name_plural': '৬. প্রতিষ্ঠান প্রধান'},
        ),
        migrations.AlterModelOptions(
            name='staff',
            options={'verbose_name': 'কর্মচারী', 'verbose_name_plural': '৮. কর্মচারীবৃন্দ'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ['order'], 'verbose_name_plural': '৫. সকল তালিকা'},
        ),
        migrations.AddField(
            model_name='teacher',
            name='teacher_type',
            field=models.CharField(choices=[('HEAD', 'প্রতিষ্ঠান প্রধান'), ('TEACHER', 'সহকারী শিক্ষক'), ('STAFF', 'কর্মচারী')], default='TEACHER', max_length=10, verbose_name='ধরণ'),
        ),
    ]
