# Generated by Django 6.0.4 on 2026-04-26 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_alter_aboutimage_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ইভেন্টের নাম (ফোল্ডার)')),
                ('cover_image', models.ImageField(upload_to='gallery/covers/', verbose_name='কভার ফটো')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': '৩. গ্যালারি ইভেন্ট/ফোল্ডার',
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/photos/', verbose_name='ছবি')),
                ('caption', models.CharField(blank=True, max_length=100, verbose_name='ছবির ক্যাপশন')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main_app.gallerycategory')),
            ],
            options={
                'verbose_name_plural': 'গ্যালারি ছবিসমূহ',
            },
        ),
        migrations.DeleteModel(
            name='Gallery',
        ),
    ]
