# Generated by Django 6.0.4 on 2026-04-26 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_gallerycategory_galleryimage_delete_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='ছবির শিরোনাম')),
                ('image', models.ImageField(upload_to='gallery/', verbose_name='ছবি')),
                ('is_featured', models.BooleanField(default=False, verbose_name='হোমপেজে দেখাবে?')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': '৩. ফটোগ্যালারি',
            },
        ),
        migrations.RemoveField(
            model_name='galleryimage',
            name='category',
        ),
        migrations.DeleteModel(
            name='GalleryCategory',
        ),
        migrations.DeleteModel(
            name='GalleryImage',
        ),
    ]
