# Generated by Django 6.0.4 on 2026-04-27 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_gallerycategory_galleryimage_delete_gallery_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='নাম')),
                ('phone', models.CharField(max_length=15, verbose_name='মোবাইল নম্বর')),
                ('subject', models.CharField(max_length=200, verbose_name='বিষয়')),
                ('message', models.TextField(verbose_name='বার্তা/অভিযোগ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='জমার সময়')),
            ],
            options={
                'verbose_name_plural': '৯. প্রাপ্ত অভিযোগ ও বার্তা',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='schoolinfo',
            options={'verbose_name_plural': '৪. বিদ্যালয় পরিচিতি ও তথ্য'},
        ),
        migrations.AddField(
            model_name='schoolinfo',
            name='address',
            field=models.CharField(default='বয়রা, খুলনা, বাংলাদেশ', max_length=255, verbose_name='ঠিকানা'),
        ),
        migrations.AddField(
            model_name='schoolinfo',
            name='email',
            field=models.EmailField(default='info@example.com', max_length=254, verbose_name='অফিসিয়াল ইমেইল'),
        ),
        migrations.AddField(
            model_name='schoolinfo',
            name='facebook_url',
            field=models.URLField(blank=True, null=True, verbose_name='ফেসবুক পেজ লিঙ্ক'),
        ),
        migrations.AddField(
            model_name='schoolinfo',
            name='map_url',
            field=models.TextField(blank=True, null=True, verbose_name='গুগল ম্যাপ এমবেড লিঙ্ক (iframe code)'),
        ),
        migrations.AddField(
            model_name='schoolinfo',
            name='phone_alt',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='বিকল্প ফোন নম্বর'),
        ),
        migrations.AddField(
            model_name='schoolinfo',
            name='phone_main',
            field=models.CharField(default='+৮৮০', max_length=20, verbose_name='প্রধান ফোন নম্বর'),
        ),
        migrations.AddField(
            model_name='schoolinfo',
            name='youtube_url',
            field=models.URLField(blank=True, null=True, verbose_name='ইউটিউব চ্যানেল লিঙ্ক'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='ইমেইল'),
        ),
    ]
