# Generated by Django 6.0.4 on 2026-04-27 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_contactmessage_alter_schoolinfo_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schoolinfo',
            options={'verbose_name_plural': '৪. বিদ্যালয় পরিচিতি ও তথ্য'},
        ),
        migrations.AddField(
            model_name='notice',
            name='file',
            field=models.FileField(default='', help_text='নোটিশের পিডিএফ ফাইলটি এখানে আপলোড করুন', upload_to='notices/', verbose_name='পিডিএফ ফাইল (PDF)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notice',
            name='show_on_dashboard',
            field=models.BooleanField(default=False, verbose_name='ড্যাশবোর্ডে দেখাবে?'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='জমার সময়'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='subject',
            field=models.CharField(max_length=200, verbose_name='বিষয়'),
        ),
        migrations.AlterField(
            model_name='gallerycategory',
            name='name',
            field=models.CharField(max_length=100, verbose_name='イভেন্টের নাম (ফোল্ডার)'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='বিস্তারিত'),
        ),
        migrations.AlterField(
            model_name='schoolinfo',
            name='address',
            field=models.CharField(default='বয়রা, খুলনা, বাংলাদেশ', max_length=255, verbose_name='ঠিকানা'),
        ),
        migrations.AlterField(
            model_name='schoolinfo',
            name='email',
            field=models.EmailField(default='info@example.com', max_length=254, verbose_name='অফিসিয়াল ইমেইল'),
        ),
    ]
