# Generated by Django 6.0.4 on 2026-04-27 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_alter_schoolinfo_options_notice_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='show_on_ticker',
            field=models.BooleanField(default=False, verbose_name='নিউজ টিকারে (সর্বশেষ) দেখাবে?'),
        ),
        migrations.AlterField(
            model_name='gallerycategory',
            name='name',
            field=models.CharField(max_length=100, verbose_name='ইভেন্টের নাম (ফোল্ডার)'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='প্রকাশের তারিখ'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='file',
            field=models.FileField(upload_to='notices/', verbose_name='পিডিএফ ফাইল (PDF)'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='show_on_dashboard',
            field=models.BooleanField(default=False, verbose_name='হোমপেজ নোটিশ বোর্ডে দেখাবে?'),
        ),
    ]
