# Generated by Django 6.0.4 on 2026-04-27 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_notice_show_on_ticker_alter_gallerycategory_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamRoutine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='পরীক্ষার শিরোনাম (উদা: বার্ষিক পরীক্ষা ২০২৬)')),
                ('target_class', models.CharField(choices=[('6', 'ষষ্ঠ শ্রেণী'), ('7', 'সপ্তম শ্রেণী'), ('8', 'অষ্টম শ্রেণী'), ('9', 'নবম শ্রেণী'), ('10', 'দশম শ্রেণী')], max_length=2, verbose_name='শ্রেণী নির্বাচন করুন')),
                ('pdf_file', models.FileField(upload_to='exam_routines/', verbose_name='রুটিন পিডিএফ (PDF)')),
                ('show_on_ticker', models.BooleanField(default=True, verbose_name='নিউজ টিকারে দেখাবে?')),
                ('show_on_notice', models.BooleanField(default=True, verbose_name='নোটিশ বোর্ডে দেখাবে?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='আপলোডের তারিখ')),
            ],
            options={
                'verbose_name_plural': '৬. পরীক্ষার রুটিন',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='generalteacher',
            options={'verbose_name': 'সহকারী শিক্ষক', 'verbose_name_plural': '৮. সহকারী শিক্ষকবৃন্দ'},
        ),
        migrations.AlterModelOptions(
            name='headmaster',
            options={'verbose_name': 'প্রতিষ্ঠান প্রধান', 'verbose_name_plural': '৭. প্রতিষ্ঠান প্রধান'},
        ),
        migrations.AlterModelOptions(
            name='staff',
            options={'verbose_name': 'কর্মচারী', 'verbose_name_plural': '৯. কর্মচারীবৃন্দ'},
        ),
        migrations.AlterField(
            model_name='teacher',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='イমেইল'),
        ),
    ]
