# Generated by Django 6.0.4 on 2026-04-27 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_examroutine_alter_generalteacher_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentCornerData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='ফাইলের শিরোনাম')),
                ('category', models.CharField(choices=[('INFO', 'শ্রেণী ও লিঙ্গভিত্তিক শিক্ষার্থী তথ্য'), ('SEAT', 'শ্রেণী ভিত্তিক আসন সংখ্যা'), ('DRESS', 'স্কুল-কলেজের ড্রেস সম্পর্কিত তথ্য'), ('CLASS_ROUTINE', 'ক্লাস রুটিন'), ('SYLLABUS', 'সিলেবাস'), ('HOLIDAY', 'ছুটির তালিকা')], max_length=20, verbose_name='ক্যাটাগরি নির্বাচন করুন')),
                ('pdf_file', models.FileField(upload_to='student_corner/pdfs/', verbose_name='PDF ফাইল আপলোড করুন')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='আপলোডের তারিখ')),
            ],
            options={
                'verbose_name_plural': '৭. শিক্ষার্থী কর্নার তথ্য (সিলেবাস, রুটিন ইত্যাদি)',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'ordering': ['-created_at'], 'verbose_name_plural': '১১. প্রাপ্ত অভিযোগ ও বার্তা'},
        ),
        migrations.AlterModelOptions(
            name='generalteacher',
            options={'verbose_name': 'সহকারী শিক্ষক', 'verbose_name_plural': '৯. সহকারী শিক্ষকবৃন্দ'},
        ),
        migrations.AlterModelOptions(
            name='headmaster',
            options={'verbose_name': 'প্রতিষ্ঠান প্রধান', 'verbose_name_plural': '৮. প্রতিষ্ঠান প্রধান'},
        ),
        migrations.AlterModelOptions(
            name='staff',
            options={'verbose_name': 'কর্মচারী', 'verbose_name_plural': '১০. কর্মচারীবৃন্দ'},
        ),
        migrations.AlterField(
            model_name='teacher',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='ইমেইল'),
        ),
    ]
