# Generated by Django 6.0.4 on 2026-04-27 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0018_studentcornerdata_alter_contactmessage_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='ফাইলের শিরোনাম')),
                ('category', models.CharField(choices=[('form', 'ভর্তি আবেদন ফরম'), ('guide', 'ভর্তি নির্দেশিকা'), ('result', 'ভর্তি পরীক্ষার ফলাফল'), ('fees', 'বেতন ও ফি সমূহ')], max_length=20, verbose_name='ক্যাটাগরি')),
                ('pdf_file', models.FileField(upload_to='admission/pdfs/', verbose_name='পিডিএফ ফাইল')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='আপলোড তারিখ')),
            ],
            options={
                'verbose_name_plural': '৮. ভর্তি সংক্রান্ত তথ্য (ফরম, ফলাফল ইত্যাদি)',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'ordering': ['-created_at'], 'verbose_name_plural': '১২. প্রাপ্ত অভিযোগ ও বার্তা'},
        ),
        migrations.AlterModelOptions(
            name='generalteacher',
            options={'verbose_name': 'সহকারী শিক্ষক', 'verbose_name_plural': '১০. সহকারী শিক্ষকবৃন্দ'},
        ),
        migrations.AlterModelOptions(
            name='headmaster',
            options={'verbose_name': 'প্রতিষ্ঠান প্রধান', 'verbose_name_plural': '৯. প্রতিষ্ঠান প্রধান'},
        ),
        migrations.AlterModelOptions(
            name='staff',
            options={'verbose_name': 'কর্মচারী', 'verbose_name_plural': '১১. কর্মচারীবৃন্দ'},
        ),
    ]
