# Generated by Django 6.0.4 on 2026-04-27 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0019_admissioninfo_alter_contactmessage_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='ফলাফলের শিরোনাম (উদা: এসএসসি ফলাফল ২০২৫)')),
                ('category', models.CharField(choices=[('public', 'পাবলিক পরীক্ষার ফলাফল'), ('internal', 'স্কুল ও কলেজের ফলাফল')], max_length=20, verbose_name='ফলাফলের ধরন')),
                ('file', models.FileField(upload_to='results/pdfs/', verbose_name='ফলাফল পিডিএফ (PDF)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='প্রকাশের তারিখ')),
            ],
            options={
                'verbose_name_plural': '৯. সকল পরীক্ষার ফলাফল (পাবলিক ও অভ্যন্তরীণ)',
                'ordering': ['-created_at'],
            },
        ),
    ]
