# Generated by Django 6.0.4 on 2026-04-28 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0020_resultdata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'ordering': ['-created_at'], 'verbose_name_plural': '৪. প্রাপ্ত অভিযোগ ও বার্তা'},
        ),
        migrations.AlterModelOptions(
            name='gallerycategory',
            options={'verbose_name_plural': '৬. গ্যালারি ইভেন্ট/ফোল্ডার'},
        ),
        migrations.AlterModelOptions(
            name='generalteacher',
            options={'verbose_name': 'সহকারী শিক্ষক', 'verbose_name_plural': '২. সহকারী শিক্ষকবৃন্দ'},
        ),
        migrations.AlterModelOptions(
            name='resultdata',
            options={'ordering': ['-created_at'], 'verbose_name_plural': '১১. সকল পরীক্ষার ফলাফল (পাবলিক ও অভ্যন্তরীণ)'},
        ),
        migrations.AlterModelOptions(
            name='schoolinfo',
            options={'verbose_name_plural': '৭. বিদ্যালয় পরিচিতি ও তথ্য'},
        ),
        migrations.AlterModelOptions(
            name='slider',
            options={'verbose_name_plural': '৫. হোমপেজ স্লাইডার'},
        ),
        migrations.AlterModelOptions(
            name='staff',
            options={'verbose_name': 'কর্মচারী', 'verbose_name_plural': '৩. কর্মচারীবৃন্দ'},
        ),
        migrations.AlterModelOptions(
            name='studentcornerdata',
            options={'ordering': ['-created_at'], 'verbose_name_plural': '১০. শিক্ষার্থী কর্নার তথ্য (সিলেবাস, রুটিন ইত্যাদি)'},
        ),
    ]
