# Generated by Django 6.0.4 on 2026-05-13 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0021_alter_contactmessage_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TickerNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='খবরের শিরোনাম')),
                ('is_active', models.BooleanField(default=True, verbose_name='সক্রিয় কি না')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'টিকার নিউজ',
            },
        ),
    ]
