# Generated by Django 6.0.4 on 2026-05-13 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0022_tickernews'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TickerNews',
        ),
    ]
