# Generated by Django 6.0.4 on 2026-06-21 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0024_tickernews'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='subject',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='বিষয়'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='designation',
            field=models.CharField(blank=True, choices=[('Headmaster', 'প্রতিষ্ঠান প্রধান'), ('Assistant Headmaster', 'সহকারী প্রধান শিক্ষক'), ('Senior Teacher', 'সিনিয়র শিক্ষক'), ('Assistant Teacher', 'সহকারী শিক্ষক'), ('Office Staff', 'অফিস স্টাফ'), ('Clerk', 'ক্লার্ক'), ('Accountant', 'হিসাবরক্ষক')], max_length=50, verbose_name='পদবী'),
        ),
    ]
