# Generated by Django 6.0.4 on 2026-06-22 04:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0025_teacher_subject_alter_teacher_designation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='designation',
            field=models.CharField(blank=True, choices=[('Headmaster', 'প্রতিষ্ঠান প্রধান'), ('Assistant Headmaster', 'সহকারী প্রধান শিক্ষক'), ('Senior Teacher', 'সিনিয়র শিক্ষক'), ('Assistant Teacher', 'সহকারী শিক্ষক'), ('Office Staff', 'অফিস স্টাফ'), ('Clerk', 'ক্লার্ক'), ('Accountant', 'হিসাবরক্ষক'), ('Night Guard', 'নৈশ প্রহরী'), ('Cleaner', 'পরিচ্ছন্ন কর্মী'), ('Aya', 'আয়া')], max_length=50, verbose_name='পদবী'),
        ),
        migrations.CreateModel(
            name='TeacherNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='শিরোনাম')),
                ('description', models.TextField(verbose_name='বিস্তারিত বর্ণনা')),
                ('is_active', models.BooleanField(default=True, verbose_name='সক্রিয়')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='প্রকাশের তারিখ ও সময়')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='সম্পাদনার তারিখ ও সময়')),
                ('posted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='প্রকাশক')),
            ],
            options={
                'verbose_name_plural': '১২. শিক্ষক ঘোষণা/খবর',
                'ordering': ['-created_at'],
            },
        ),
    ]
