# Generated by Django 6.0.4 on 2026-06-22 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0027_alter_admissioninfo_category_delete_teachernews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissioninfo',
            name='category',
            field=models.CharField(choices=[('form', 'ভর্তি আবেদন ফরম'), ('guide', 'ভর্তি নির্দেশিকা'), ('result', 'ভর্তি পরীক্ষার ফলাফল'), ('exam_routine', 'পরীক্ষার রুটিন'), ('fees', 'বেতন ও ফি সমূহ')], max_length=20, verbose_name='ক্যাটাগরি'),
        ),
    ]
