# Generated by Django 6.0.4 on 2026-06-22 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0028_alter_admissioninfo_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissioninfo',
            name='category',
            field=models.CharField(choices=[('form', 'ভর্তি আবেদন ফরম'), ('guide', 'ভর্তি নির্দেশিকা'), ('result', 'ভর্তি পরীক্ষার ফলাফল'), ('fees', 'বেতন ও ফি সমূহ')], max_length=20, verbose_name='ক্যাটাগরি'),
        ),
        migrations.AlterField(
            model_name='studentcornerdata',
            name='category',
            field=models.CharField(choices=[('INFO', 'শ্রেণী ও লিঙ্গভিত্তিক শিক্ষার্থী তথ্য'), ('SEAT', 'শ্রেণী ভিত্তিক আসন সংখ্যা'), ('DRESS', 'স্কুল-কলেজের ড্রেস সম্পর্কিত তথ্য'), ('CLASS_ROUTINE', 'ক্লাস রুটিন'), ('SYLLABUS', 'সিলেবাস'), ('EXAM_ROUTINE', 'পরীক্ষার রুটিন'), ('HOLIDAY', 'ছুটির তালিকা')], max_length=20, verbose_name='ক্যাটাগরি নির্বাচন করুন'),
        ),
    ]
