# Generated by Django 6.0.4 on 2026-06-24 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0029_alter_admissioninfo_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='teachers/', verbose_name='স্বাক্ষর (প্রতিষ্ঠান প্রধানের জন্য)'),
        ),
    ]
