# Generated by Django 6.0.4 on 2026-06-29 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0030_teacher_signature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='signature',
        ),
    ]
