# Generated by Django 5.2.2 on 2026-07-16 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0031_remove_teacher_signature'),
        ('main_app', '0033_reconcile_teacher_signature_migration'),
    ]

    operations = [
    ]
