# Generated by Django 5.2.2 on 2026-07-04 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0032_merge_20260704_0000'),
        ('main_app', '0033_reconcile_teacher_signature_migration'),
    ]

    operations = [
    ]
