# Generated by Django 5.2.2 on 2026-07-27 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0034_merge_20260716_0634'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_uuid', models.CharField(db_index=True, max_length=64, unique=True)),
                ('ip_address', models.CharField(max_length=45, verbose_name='আইপি ঠিকানা')),
                ('first_visit', models.DateTimeField(auto_now_add=True, verbose_name='প্রথম ভিজিট')),
                ('last_visit', models.DateTimeField(auto_now=True, verbose_name='সর্বশেষ ভিজিট')),
            ],
            options={
                'verbose_name_plural': 'ভিজিটর প্রোফাইল',
            },
        ),
        migrations.CreateModel(
            name='DailyVisitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='তারিখ')),
                ('ip_address', models.CharField(max_length=45, verbose_name='আইপি ঠিকানা')),
                ('session_key', models.CharField(max_length=40, verbose_name='সেশন কী')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='সৃষ্টি সময়')),
                ('visitor_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_visits', to='main_app.visitorprofile')),
            ],
            options={
                'verbose_name_plural': 'দৈনিক ভিজিটর',
                'indexes': [models.Index(fields=['date'], name='main_app_da_date_a8d2d7_idx'), models.Index(fields=['ip_address', 'session_key'], name='main_app_da_ip_addr_1d3941_idx')],
                'unique_together': {('date', 'ip_address', 'session_key')},
            },
        ),
    ]
