# Generated by Django 6.0.4 on 2026-07-16 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0032_merge_20260704_0000'),
        ('main_app', '0034_merge_20260704_0717'),
    ]

    operations = [
    ]
