# Generated by Django 5.1.3 on 2026-07-30 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0035_visitorprofile_dailyvisitor"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="dailyvisitor",
            new_name="main_app_daily_date_idx",
            old_name="main_app_da_date_a8d2d7_idx",
        ),
        migrations.RenameIndex(
            model_name="dailyvisitor",
            new_name="main_app_daily_vis_idx",
            old_name="main_app_da_ip_addr_1d3941_idx",
        ),
        migrations.AlterField(
            model_name="visitorprofile",
            name="visitor_uuid",
            field=models.CharField(
                db_index=True, max_length=64, unique=True, verbose_name="ভিজিটর ইউইডি"
            ),
        ),
    ]
