# Generated by Django 6.0.4 on 2026-09-22 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0036_rename_main_app_da_date_a8d2d7_idx_main_app_daily_date_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolinfo',
            name='committee_designation',
            field=models.CharField(default='সভাপতি', max_length=100, verbose_name='ম্যানেজিং কমিটির পদবি'),
        ),
        migrations.AddField(
            model_name='schoolinfo',
            name='committee_image',
            field=models.ImageField(blank=True, null=True, upload_to='school_info/committee/', verbose_name='ম্যানেজিং কমিটির ছবি'),
        ),
        migrations.AddField(
            model_name='schoolinfo',
            name='committee_name',
            field=models.CharField(default='ম্যানেজিং কমিটির সভাপতি', max_length=100, verbose_name='ম্যানেজিং কমিটির নাম'),
        ),
        migrations.AddField(
            model_name='schoolinfo',
            name='headmaster_designation',
            field=models.CharField(default='প্রধান শিক্ষক', max_length=100, verbose_name='প্রধান শিক্ষকের পদবি'),
        ),
        migrations.AddField(
            model_name='schoolinfo',
            name='headmaster_image',
            field=models.ImageField(blank=True, null=True, upload_to='school_info/headmaster/', verbose_name='প্রধান শিক্ষকের ছবি'),
        ),
        migrations.AddField(
            model_name='schoolinfo',
            name='headmaster_name',
            field=models.CharField(default='মোঃ সেলিম সরদার', max_length=100, verbose_name='প্রধান শিক্ষকের নাম'),
        ),
    ]
