# Generated by Django 6.0.4 on 2026-09-22 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0037_schoolinfo_committee_designation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadershipProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_type', models.CharField(choices=[('HEADMASTER', 'প্রধান শিক্ষক'), ('MANAGING_COMMITTEE', 'ম্যানেজিং কমিটি')], max_length=25, unique=True, verbose_name='প্রোফাইলের ধরন')),
                ('name', models.CharField(max_length=100, verbose_name='নাম')),
                ('designation', models.CharField(max_length=100, verbose_name='পদবি')),
                ('image', models.ImageField(upload_to='leadership/', verbose_name='ছবি')),
                ('message', models.TextField(blank=True, verbose_name='বার্তা')),
            ],
            options={
                'verbose_name': 'প্রধান শিক্ষক/ম্যানেজিং কমিটি',
                'verbose_name_plural': 'প্রধান শিক্ষক/ম্যানেজিং কমিটি',
            },
        ),
        migrations.RemoveField(
            model_name='schoolinfo',
            name='committee_designation',
        ),
        migrations.RemoveField(
            model_name='schoolinfo',
            name='committee_image',
        ),
        migrations.RemoveField(
            model_name='schoolinfo',
            name='committee_name',
        ),
        migrations.RemoveField(
            model_name='schoolinfo',
            name='headmaster_designation',
        ),
        migrations.RemoveField(
            model_name='schoolinfo',
            name='headmaster_image',
        ),
        migrations.RemoveField(
            model_name='schoolinfo',
            name='headmaster_name',
        ),
    ]
