# Generated by Django 6.0.4 on 2026-09-22 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0038_leadershipprofile_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leadershipprofile',
            options={'verbose_name': 'প্রধান শিক্ষক ও ম্যানেজিং কমিটি', 'verbose_name_plural': 'প্রধান শিক্ষক ও ম্যানেজিং কমিটি'},
        ),
        migrations.RemoveField(
            model_name='leadershipprofile',
            name='message',
        ),
        migrations.AlterField(
            model_name='leadershipprofile',
            name='designation',
            field=models.CharField(max_length=150, verbose_name='পদবি'),
        ),
        migrations.AlterField(
            model_name='leadershipprofile',
            name='name',
            field=models.CharField(max_length=150, verbose_name='নাম'),
        ),
        migrations.AlterField(
            model_name='leadershipprofile',
            name='profile_type',
            field=models.CharField(choices=[('HEADMASTER', 'প্রধান শিক্ষক'), ('COMMITTEE', 'ম্যানেজিং কমিটি')], max_length=20, unique=True, verbose_name='প্রোফাইলের ধরন'),
        ),
    ]
