# Generated by Django 6.0.4 on 2026-09-22 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0039_alter_leadershipprofile_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadershipprofile',
            name='caption',
            field=models.TextField(blank=True, verbose_name='ক্যাপশন/বার্তা'),
        ),
    ]
