# Generated by Django 6.1.2 on 2026-10-07 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0042_notice_is_new'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntryPopupImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='ছবির শিরোনাম (ঐচ্ছিক)')),
                ('image', models.ImageField(upload_to='welcome_slider/', verbose_name='ছবি')),
                ('is_active', models.BooleanField(default=True, verbose_name='অ্যাক্টিভ আছে?')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ক্রম')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='তৈরির তারিখ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='সর্বশেষ আপডেট')),
            ],
            options={
                'verbose_name': 'Welcome Slider',
                'verbose_name_plural': 'Welcome Slider',
                'ordering': ['order', 'pk'],
            },
        ),
    ]
