# Generated by Django 6.1.2 on 2026-10-07 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0044_alter_leadershipprofile_profile_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolinfo',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='সর্বশেষ আপডেট'),
        ),
    ]
